### ISSUE TITLE
HeySMS selects self-created Bonjour contact IDs

### ISSUE THREAD

**Issue by ossi1967** [titilambert/HeySms#4]
Not a priority, but: After the initial start, when you have received at least one SMS, HeySMS creates a new Bonjour contact for the sender. Unfortunately, when you refresh and select the Bonjour contact ID to use from the HeySMS main screen, this freshly created Bonjour account is available where only a PC with a running XMPP client should be visible.

Usually people will not refresh this list while the program is running, but still... maybe there's a possibility to not show contacts that were created by HeySMS itself.

**Comment by titilambert** [comment]
Fixed !
