### ISSUE TITLE
Idea: Add options to initiate SMS conversation

### ISSUE THREAD

**Issue by ossi1967** [titilambert/HeySms#5]
As I understand it, HeySMS can be used to answer incoming SMS. There's no way to initiate a conversation from the PC. (Right?)

There could be ways to do this. 

Idea 1: 
Use a permanent account "HeySMS control" that accepts commands like IRC-bots do. Commands could be "search brian" (search all contacts that contain the string 'brian'; create a temporary account for each of them), "create +123456" (create a temporary account for phone number +123456). anything that's not a command should result in a short help text being returned as an answer.

Idea 2:
Make an option in the HeySMS application itself to expose the address book - or parts of it - at startup.

**Comment by titilambert** [comment]
Hello !
Maybe I can do both ? L)
What do you think ?

**Comment by ossi1967** [comment]
Sure, if you _can_ do both :)

I always like choices.

**Comment by titilambert** [comment]
@ossi1967 
DONE ! in version 1.6.1 !

Thanks !
